### ISSUE TITLE
index 17xx is out of bounds 

### ISSUE THREAD

**Issue by Chengwei-Yan** [Zafar-Lab/scDREAMER#5] opened 2024-01-30 04:01 UTC
batch_x_[:,rand_inx] = 0
   
IndexError: index 17xx is out of bounds for axis 1 with size 14xx
Hello, may I ask you according to the tutorial h5ad file and batch label passed to scDREAMER API, why will the error dimension does not meet, it is not supposed to occur such bug

**Comment by ajitashree** [comment] 2024-06-19 03:38
Hello,

Thanks for using scDREAMER. You need to give batch information key to the scDREAMER (see snapshot of the tutorial) and then the code should run fine.

Please also see if the version of numpy and random are same as suggested for scDREAMER. The above error is likely due to version mismatch.

<img width="736" alt="Screenshot 2024-06-19 at 9 04 23 AM" src="https://github.com/Zafar-Lab/scDREAMER/assets/13568525/600b4354-7882-4b2d-ba11-84684736fd74">

**Comment by ajitashree** [comment] 2024-07-10 06:04
Closing the issue as the issue is arising due to version mismatch.

**Closed as completed by ajitashree** 2024-07-10 06:04 UTC
